## Упражнения по библиотеке Numpy

In [13]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [15]:
#1
import numpy.random as rand
a = np.array(rand.randint(0, 10, 11))
print(a)
for i in range(len(a)):
    if 3 < a[i] < 8:
        a[i] = - a[i]
print(a)
#2
Z = np.arange(11)
print(Z)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[9 2 0 3 5 9 7 4 3 6 0]
[ 9  2  0  3 -5  9 -7 -4  3 -6  0]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


**2.** Заменить максимальный элемент случайного массива на 0

In [16]:
import numpy.random as rand
a = np.array(rand.randint(0, 10, 11))
print(a)
max_value = np.max(a)
for i in range(len(a)):
    if a[i] == max_value:
        a[i] = 0
print(a)
#второе решение
z = rand.random(10)
print(z)
z[z.argmax()] = 0
print(z)
#второе подходит для многомерного массива
d = rand.random(10)
print(d)
d[d == d.max()] = 0
print(d)

[4 4 1 8 3 7 2 5 1 9 6]
[4 4 1 8 3 7 2 5 1 0 6]
[0.23094459 0.31870805 0.40781164 0.67841927 0.57093825 0.9184381
 0.83357175 0.83664664 0.35451633 0.5886426 ]
[0.23094459 0.31870805 0.40781164 0.67841927 0.57093825 0.
 0.83357175 0.83664664 0.35451633 0.5886426 ]
[0.42762462 0.30700814 0.33377764 0.02484644 0.93712792 0.90933943
 0.5425211  0.03906068 0.63193229 0.90008606]
[0.42762462 0.30700814 0.33377764 0.02484644 0.         0.90933943
 0.5425211  0.03906068 0.63193229 0.90008606]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [140]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian( [ [1, 2, 3], [4, 5] ] ))

[[1 4]
 [1 5]
 [2 4]
 [2 5]
 [3 4]
 [3 5]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [98]:
import numpy.random as rand
A = rand.randint(0,5,(8,3))
B = rand.randint(0,5,(2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[0 4 0]
 [1 4 1]
 [4 1 1]
 [2 3 0]
 [2 3 0]
 [3 3 0]
 [3 4 2]
 [0 3 2]]
[[1 3]
 [1 4]]
[1 2 5 6]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [89]:
import numpy.random as rand
Z = rand.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 4 4]
 [3 2 2]
 [0 0 4]
 [2 4 4]
 [2 3 3]
 [4 3 1]
 [1 3 2]
 [3 2 4]
 [4 3 1]
 [4 0 4]]
[[3 2 2]
 [0 0 4]
 [2 4 4]
 [2 3 3]
 [4 3 1]
 [1 3 2]
 [3 2 4]
 [4 3 1]
 [4 0 4]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [42]:
import numpy.random as rand
Z = rand.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(Z)
print(uZ)

[[1 1 0]
 [1 0 1]
 [1 1 1]
 [0 0 1]
 [0 1 1]
 [0 0 0]]
[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [78]:
#1
x = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
res = np.prod(np.diag(x)[np.diag(x)!=0])
print(res)

#2
x = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
n = len(x[0]) #столбцы
m = len(x)  #строки
f = 1
for i in range(m):
   for j in range(n):
      if i == j and x[i][j] != 0: #диагональ + !=0
         f *= x[i][j] 
print(f)

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [32]:
#1
x = np.array([1,2,2,4])
y = np.array([4,2,1,2])
x_nums, x_counts = np.unique(x, return_counts=True)
y_nums, y_counts = np.unique(y, return_counts=True)
if(np.shape(x_nums) != np.shape(y_nums)):
    print(False)
if(np.any(x_nums != y_nums) or np.any(x_counts != y_counts)):
    print(False)
print(True)

#2
x = ([1,2,2,4])
y = ([4,2,1,2])
if(len(x) != len(y)):
    print(False)
x.sort()
y.sort()
for i in range(len(x)):
    if(x[i] != y[i]):
        print(False)
print(True)

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [31]:
#1
x = np.array([6,2,0,3,0,0,5,7,0])
curr = np.ones((1))
curr = np.hstack((curr, x))
ind = curr == 0
result = np.max(x[ind[:-1]])
print(result) 

#2
x = ([6,2,0,3,0,0,5,7,0])
after_zero_list = list()
for i in range(1, len(x)):
    if(not x[i - 1]):
        after_zero_list.append(x[i])
result = max(after_zero_list)
print(result)  

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [30]:
#1
x = np.array([2,2,2,3,3,3,5])
y = np.hstack((np.ones(1), x[:- 1]))
first_positions = x != y
first_positions[0] = True
indexes_1 = np.arange(np.size(x))[first_positions]
indexes_2 = np.hstack((indexes_1[1:], np.array([np.size(x)])))
result = x[first_positions], indexes_2 - indexes_1
print(result)

#2
x = ([2,2,2,3,3,3,5])
val_list = [x[0]]
num_list = list()
counter = 1
for i in range(1, len(x)):
    if(x[i - 1] == x[i]):
        counter = counter + 1
    else:
        val_list.append(x[i])
        num_list.append(counter)
        counter = 1
num_list.append(counter)
result = (val_list, num_list)
print(result)

(array([2, 3, 5]), array([3, 3, 1]))
([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [29]:
import math
#1 - 0.5s
X = np.array((1, 3, 4))
Y = np.array((4, 7, 1))
distance = np.sqrt(sum(pow(a-b, 2) for a, b in zip(X, Y)))
print(distance)

#2 - 0.4s
X = [(1,3,4)]
Y = [(4,7,1)]
result_matr = list()
for i in range(len(X)):
    curr_list = list()
    for j in range(len(Y)):
        dist = 0
        for k in range(len(X[0])):
            dist += (X[i][k] - Y[j][k]) ** 2
        curr_list.append(math.sqrt(dist))
    result_matr.append(curr_list)
print(result_matr)

#3 - 0.9s - работает дольше
import scipy.spatial
X = [(1,3,4)]
Y = [(4,7,1)]
D = scipy.spatial.distance.cdist(X, Y, 'euclidean')
print(D)

5.830951894845301
[[5.830951894845301]]
[[5.83095189]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [4]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [5]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
print(calorie_stats)

[ 70. 120.  70.  50. 110. 110. 110. 130.  90.  90. 120. 110. 120. 110.
 110. 110. 100. 110. 110. 110. 100. 110. 100. 100. 110. 110. 100. 120.
 120. 110. 100. 110. 100. 110. 120. 120. 110. 110. 110. 140. 110. 100.
 110. 100. 150. 150. 160. 100. 120. 140.  90. 130. 120. 100.  50.  50.
 100. 100. 120. 100.  90. 110. 110.  80.  90.  90. 110. 110.  90. 110.
 140. 100. 110. 110. 100. 100. 110.]


2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [6]:
calorie_mean = np.mean(calorie_stats) # мы могли бы использовать np.average, но по важности все значения тут одинаковы, поэтому mean
crunchie_calories = 60
average_calories = calorie_mean - crunchie_calories
print(calorie_mean)
print(average_calories)

106.88311688311688
46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [7]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [8]:
median_calories = np.median(calorie_stats_sorted)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [9]:
x = np.percentile(calorie_stats_sorted, 50) #медиана
print(x)
x = np.percentile(calorie_stats_sorted, 30)
print(x)
x = np.percentile(calorie_stats_sorted, 10)
print(x)
x = np.percentile(calorie_stats_sorted, 5)
print(x)
x = np.percentile(calorie_stats_sorted, 4) #нужное значение
print(x)
x = np.percentile(calorie_stats_sorted, 3) #уже меньше 60
print(x)
nth_percentile = np.percentile(calorie_stats_sorted, 4)
print(nth_percentile)

110.0
100.0
90.0
70.0
70.0
55.599999999999994
70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [10]:
more_calories = np.mean(calorie_stats > 60) * 100 #проценты
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [11]:
calorie_std = np.std(calorie_stats)
print(calorie_std)
#это показывает, что отклонение от среднего значения (110 калорий) это примерно 20 калорий. в большинстве злаков более 100 калорий, поэтому разброс больше
#можем это включить в анализ, чтобы показать диапазон изменений других продуктов на рынке

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [12]:
print(len(calorie_stats))
#согласно вышеприведенным исследованиям, мы можем наглядно видеть, как наш продукт выгодно выделяется на фоне остальных. 96 процентов из 77 рассмотренных продуктов имеют большую калорийность, значит мы можем продвигать наши хлопья как диетический низкокалорийный продукт. это значит, что они не только вкусные и полезные, но и могут помочь вам сбросить вес или же держать себя в форме! 

77
